# Simple pre-commit configuration for Langvio
# Matches basic CI checks only

repos:
  # Black - code formatting (matches CI)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [ "--check", "--line-length=88" ]
        files: ^langvio/

  # MyPy - type checking (optional, matches CI)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [ "--ignore-missing-imports" ]
        files: ^langvio/
        additional_dependencies: [ types-all ]
        # Make mypy optional (non-blocking) like in CI
        verbose: true
        stages: [ manual ]

# Configuration
default_language_version:
  python: python3.12

# Only run black and isort by default (like CI)
default_stages: [ commit ]

# Minimum pre-commit version
minimum_pre_commit_version: "3.0.0"